-- this file is auto-generated by BigWigs Packager from CurseForge localizations
local L = select(2, ...).L('esES') -- luacheck: ignore
--@localization(locale="esES", format="lua_additive_table", handle-unlocalized="blank")@
