-- this file is auto-generated by BigWigs Packager from CurseForge localizations
local L = select(2, ...).L('esMX') -- luacheck: ignore
--@localization(locale="esMX", format="lua_additive_table", handle-unlocalized="blank")@
