-- this file is auto-generated by BigWigs Packager from CurseForge localizations
local L = select(2, ...).L('frFR') -- luacheck: ignore
--@localization(locale="frFR", format="lua_additive_table", handle-unlocalized="blank")@
