-- this file is auto-generated by BigWigs Packager from CurseForge localizations
local L = select(2, ...).L('itIT') -- luacheck: ignore
--@localization(locale="itIT", format="lua_additive_table", handle-unlocalized="blank")@
