-- this file is auto-generated by BigWigs Packager from CurseForge localizations
local L = select(2, ...).L('ptBR') -- luacheck: ignore
--@localization(locale="ptBR", format="lua_additive_table", handle-unlocalized="blank")@
