-- this file is auto-generated by BigWigs Packager from CurseForge localizations
local L = select(2, ...).L('ruRU') -- luacheck: ignore
--@localization(locale="ruRU", format="lua_additive_table", handle-unlocalized="blank")@
