-- this file is auto-generated by BigWigs Packager from CurseForge localizations
local L = select(2, ...).L('zhCN') -- luacheck: ignore
--@localization(locale="zhCN", format="lua_additive_table", handle-unlocalized="blank")@
