-- this file is auto-generated by BigWigs Packager from CurseForge localizations
local L = select(2, ...).L('zhTW') -- luacheck: ignore
--@localization(locale="zhTW", format="lua_additive_table", handle-unlocalized="blank")@
