name: Scrape classic era

on:
  push:
    branches:
      - master
    tags-ignore:
      - '**'
    paths:
      - 'scripts/**.py'
  schedule:
    - cron: '0 8 * * 1' # monday morning
  workflow_dispatch:

jobs:
  scrape:
    uses: ./.github/workflows/scrape.yaml
    with:
      flavor: classic_era
      dbc: wow_classic_era_latest
      files: |
        openable: openable_classic_era
        keys_classic_era: keys_classic_era
        nondisenchantable: nondisenchantable_classic_era
