name: Scrape classic

on:
  push:
    branches:
      - master
    tags-ignore:
      - '**'
    paths:
      - 'scripts/**.py'
  schedule:
    - cron: '0 8 * * 1' # monday morning
  workflow_dispatch:

jobs:
  scrape:
    uses: ./.github/workflows/scrape.yaml
    with:
      flavor: classic
      dbc: wow_classic_ptr_latest
      files: |
        openable: openable_classic
        keys_classic: keys_classic
        nondisenchantable: nondisenchantable_classic
        prospectable_classic: prospectable_classic
        millable_classic: millable_classic
