name: Update translation issue template

on:
  push:
    branches:
      - master
    tags-ignore:
      - '**'

jobs:
  template:
    runs-on: ubuntu-latest
    steps:
      - name: Clone project
        uses: actions/checkout@v4

      - name: Update issue template
        uses: p3lim/lua-translations@master
        with:
          action: template

      - name: Create pull request
        uses: peter-evans/create-pull-request@v7
        with:
          title: Update translation issue template
          body:
          commit-message: Update translation issue template
          branch: translation-issue-template
          delete-branch: true
